### ISSUE TITLE
Ops Agent is spamming Google Cloud Logger with rsyslogd suspended/resumed messages

### ISSUE THREAD

**Issue by AndrewDryga** [GoogleCloudPlatform/ops-agent#1694] opened 2024-05-02 20:48 UTC
**Describe the bug**
Ops Agent is spamming our logs with messages like this one:
```
May  2 18:46:18 gateway-gbmt rsyslogd: action 'action-8-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2112.0 try https://www.rsyslog.com/e/2007 ]
May  2 18:46:18 gateway-gbmt rsyslogd: action 'action-8-builtin:omfile' resumed (module 'builtin:omfile') [v8.2112.0 try https://www.rsyslog.com/e/2359 ]
```

**To Reproduce**

We are using Ubuntu 22.04 LTS, you can find the terraform module that we are using to deploy one-off workloads [here](https://github.com/firezone/firezone/tree/main/terraform/modules/google-cloud/apps/vm), the Ops Agent is installed [here](https://github.com/firezone/firezone/blob/main/terraform/modules/google-cloud/apps/gateway-region-instance-group/templates/cloud-init.yaml#L42). There were nothing additional on the VM.

**Expected behavior**

**Environment (please complete the following information):**
 - Project ID: firezone-prod
 - VM ID: 484420074399023514
 - VM distro / OS: Ubuntu 22.04
 - Ops Agent version: 2.46.1
 - Ops Agent configuration: https://github.com/firezone/firezone/blob/main/terraform/modules/google-cloud/apps/gateway-region-instance-group/templates/cloud-init.yaml#L22
 - Ops Agent log:
```
DEBUG 2024-05-02T19:52:15.683220945Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
DEBUG 2024-05-02T20:02:15.683225172Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
DEBUG 2024-05-02T20:12:15.683214424Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
DEBUG 2024-05-02T20:22:15.683194421Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
DEBUG 2024-05-02T20:32:15.683245922Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
DEBUG 2024-05-02T20:42:15.683201689Z [resource.labels.instanceId: gateway-gbmt] {"code":"LogPingOpsAgent"}
```

**Comment by jefferbrecht** [comment] 2024-05-02 21:32
Hi @AndrewDryga, those logs appear to be coming from the host's syslog. The Ops Agent is merely forwarding those logs to Cloud Logging without prejudice -- there's no indication that the Ops Agent itself is creating or coercing those logs. You might find more clues by searching around for that specific log; I can see a few claims floating around of a related bug in rsyslog that can cause that spam, for example.

You can certainly configure an `exclude_logs` processor on the Ops Agent to hide them from Cloud Logging until you're able to figure out the root cause. Something like this (untested):

```yaml
logging:
  processors:
    filter_rsyslog_spam:
      type: exclude_logs
      match_any:
      - "jsonPayload.message =~ \"rsyslogd: action 'action-8-builtin:omfile'\""
  service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
        processors: [filter_rsyslog_spam]
```

**Comment by igorpeshansky** [comment] 2024-05-02 21:33
The Ops Agent is just reading the logs that are on the system. Looks like this particular one is an rsyslogd issue[^1][^2]. You can use the [`exclude_logs` filter](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-processor-exclude-logs) to remove those.

[^1]: https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/2011574
[^2]: https://bugs.launchpad.net/ubuntu/+source/sympa/+bug/1906918

**Comment by AndrewDryga** [comment] 2024-05-03 02:55
Thank you guys, really appreciate the help and how fast you responded!

**Comment by jefferbrecht** [comment] 2024-05-14 21:09
Closing this for now -- feel free to re-open if you still have any issues or questions!

**Closed by jefferbrecht** 2024-05-14 21:09 UTC
Labels: wontfix
