### ISSUE TITLE
Cannot start Logging Agent and Metrics Agent (code=exited, status=238/STATE_DIRECTORY)

### ISSUE THREAD

**Issue by o3661606** [GoogleCloudPlatform/ops-agent#1179] opened 2023-03-29 09:59 UTC
**Describe the bug**
Cannot start Logging Agent and Metrics Agent (code=exited, status=238/STATE_DIRECTORY)

**Expected behavior**
All 4 services started without error

**Environment (please complete the following information):**
 - VM distro / OS: rhel 8
 - Linux version: Linux appsrv01-dev 4.18.0-193.14.3.el8_2.x86_64 # 1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Ops Agent version 2.29.0-1.el8
 - Ops Agent configuration: using Built-in config, no custom configuration file
 - Ops Agent log

**Result of `sudo journalctl -xe | grep "google_cloud_ops_agent_engine"`**
```
Mar 29 17:34:25 appsrv01-dev systemd[258025]: google-cloud-ops-agent-opentelemetry-collector.service: Failed at step STATE_DIRECTORY spawning /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine: Permission denied
-- Subject: Process /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine could not be executed
-- The process /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine could not be executed and failed.
Mar 29 17:34:25 appsrv01-dev systemd[258026]: google-cloud-ops-agent-fluent-bit.service: Failed at step STATE_DIRECTORY spawning /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine: Permission denied
-- Subject: Process /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine could not be executed
-- The process /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine could not be executed and failed.
```
**Result of `sudo systemctl status google-cloud-ops-agent"*"`**

```
[user@myhost-dev ~]$ sudo systemctl status google-cloud-ops-agent"*"
● google-cloud-ops-agent.service - Google Cloud Ops Agent
   Loaded: loaded (/usr/lib/systemd/system/google-cloud-ops-agent.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2023-03-29 17:34:24 HKT; 5min ago
 Main PID: 257974 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 204300)
   Memory: 0B
   CGroup: /system.slice/google-cloud-ops-agent.service

Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]:   service:
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]:     pipelines:
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]:       default_pipeline:
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]:         receivers: [hostmetrics]
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]:         processors: [metrics_filter]
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]: 2023/03/29 17:34:24 Ports Check - Result: PASS
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]: 2023/03/29 17:34:24 Network Check - Result: PASS
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]: 2023/03/29 17:34:24 API Check - Result: PASS
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_engine[257948]: 2023/03/29 17:34:24 Startup checks finished
Mar 29 17:34:24 myhost-dev systemd[1]: Started Google Cloud Ops Agent.

● google-cloud-ops-agent-fluent-bit.service - Google Cloud Ops Agent - Logging Agent
   Loaded: loaded (/usr/lib/systemd/system/google-cloud-ops-agent-fluent-bit.service; static; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/google-cloud-ops-agent-fluent-bit.service.d
           └─directories.conf
           /etc/systemd/system/google-cloud-ops-agent-fluent-bit.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Wed 2023-03-29 17:34:26 HKT; 5min ago
  Process: 258026 ExecStartPre=/opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine -service=fluentbit -in /etc/google-cloud-ops-agent/config.yaml -logs ${LOGS_DIRECTORY} -state ${STATE_DIRECTORY} (code=exited, status=238/STATE_DIRECTORY)

Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-fluent-bit.service: Service RestartSec=100ms expired, scheduling restart.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-fluent-bit.service: Scheduled restart job, restart counter is at 7.
Mar 29 17:34:26 myhost-dev systemd[1]: Stopped Google Cloud Ops Agent - Logging Agent.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-fluent-bit.service: Start request repeated too quickly.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-fluent-bit.service: Failed with result 'exit-code'.
Mar 29 17:34:26 myhost-dev systemd[1]: Failed to start Google Cloud Ops Agent - Logging Agent.

● google-cloud-ops-agent-opentelemetry-collector.service - Google Cloud Ops Agent - Metrics Agent
   Loaded: loaded (/usr/lib/systemd/system/google-cloud-ops-agent-opentelemetry-collector.service; static; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/google-cloud-ops-agent-opentelemetry-collector.service.d
           └─directories.conf
           /etc/systemd/system/google-cloud-ops-agent-opentelemetry-collector.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Wed 2023-03-29 17:34:26 HKT; 5min ago
  Process: 258025 ExecStartPre=/opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine -service=otel -in /etc/google-cloud-ops-agent/config.yaml -logs ${LOGS_DIRECTORY} (code=exited, status=238/STATE_DIRECTORY)

Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Service RestartSec=100ms expired, scheduling restart.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Scheduled restart job, restart counter is at 7.
Mar 29 17:34:26 myhost-dev systemd[1]: Stopped Google Cloud Ops Agent - Metrics Agent.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Start request repeated too quickly.
Mar 29 17:34:26 myhost-dev systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Failed with result 'exit-code'.
Mar 29 17:34:26 myhost-dev systemd[1]: Failed to start Google Cloud Ops Agent - Metrics Agent.

● google-cloud-ops-agent-diagnostics.service - Google Cloud Ops Agent - Diagnostics
   Loaded: loaded (/usr/lib/systemd/system/google-cloud-ops-agent-diagnostics.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-03-29 17:34:24 HKT; 5min ago
 Main PID: 257959 (google_cloud_op)
    Tasks: 11 (limit: 204300)
   Memory: 26.5M
   CGroup: /system.slice/google-cloud-ops-agent-diagnostics.service
           └─257959 /opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_diagnostics -config /etc/google-cloud-ops-agent/config.yaml

Mar 29 17:34:24 myhost-dev systemd[1]: Started Google Cloud Ops Agent - Diagnostics.
Mar 29 17:34:24 myhost-dev google_cloud_ops_agent_diagnostics[257959]: 2023/03/29 17:34:24 validateWinlogV1Channels: GetOldWinlogChannels() returned err=not a Windows platform
```

**Result of directory permission `ls -ltr`**
```
[user@myhost-dev ~]$ ls -ltr /opt
total 0
drwxr-xr-x. 4 root root  38 Mar  4 01:05 google-cloud-ops-agent

[user@myhost-dev ~]$ sudo ls -ltr /opt/google-cloud-ops-agent
total 0
drwxr-xr-x. 4 root root 55 Mar  4 01:05 subagents
drwxr-xr-x. 2 root root 85 Mar 29 17:34 libexec

[user@myhost-dev ~]$ sudo ls -ltr /opt/google-cloud-ops-agent/*
/opt/google-cloud-ops-agent/subagents:
total 0
drwxr-xr-x. 5 root root 45 Mar  4 01:05 fluent-bit
drwxr-xr-x. 2 root root 74 Mar 29 17:34 opentelemetry-collector

/opt/google-cloud-ops-agent/libexec:
total 206100
-rwxr-xr-x. 1 root root 105295906 Mar 25 00:24 google_cloud_ops_agent_engine
-rwxr-xr-x. 1 root root 105743565 Mar 25 00:24 google_cloud_ops_agent_diagnostics

```
**Result of `sestatus`**
```
[user@myhost-dev ~]$ sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31
```

**Comment by braydonk** [comment] 2023-03-29 15:35
The `ls -ltr` result shows a `.`, which means there is some SELinux ACL controlling them. You will need to determine why SELinux is restricting the execution of files in that directory. You could look into it with [getfacl](https://linux.die.net/man/1/getfacl) to get more information.

Since this is appears to be an environment configuration nuance and not a bug with the Ops Agent itself, I'm going to close this issue for now. If you have any additional issues, I recommend opening a ticket with Cloud Support.

**Closed by braydonk** 2023-03-29 15:35 UTC
