### ISSUE TITLE
Docker unstructured JSON logs

### ISSUE THREAD

**Issue by PierreBart** [GoogleCloudPlatform/ops-agent#654] opened 2022-06-07 11:31 UTC
I am trying to export logs from docker containers running in GCE instances to Cloud Logging using the Ops Agent.

The container logs are structured in JSON format. These logs are stored under `/var/lib/containers/*/*-json.log`, and written using the `json-file` logging driver.

The issue is that this Docker driver writes the container outputs as a string in the field `log`, escaping each `"`.

For example, this container log output in JSON format:
```json
{
  "key": "value",
  "key2": "value2"
 }  
```
would be written in the Docker log file as such:
```json
{
  "log": "{\"key\": \"value\", \"key2\": \"value2\"}",
  "stream":"stdout",
  "time": "2022-05-25T09:32:56.206276216Z"
}
```

Regardless, I have written the following Ops agent configuration file to export the logs from containers:
```yaml
logging:
  processors:
    docker:
      field: message
      time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
      time_key: time
      type: parse_json
  receivers:
    docker:
      include_paths:
      - /var/lib/docker/containers/*/*-json.log
      type: files
  service:
    pipelines:
      default_pipeline:
        processors:
        - docker
        receivers:
        - docker
metrics:
  service:
    pipelines:
      default_pipeline:
        receivers: []
```

I expected that the `parse_json` processor would parse the `log` field and structure it in JSON like this Fluentbit parser would:
```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    Decode_Field_As    json     log
```

However, the `log` field is still interpreted as string in Cloud Logging in the `jsonPayload`:
```json
{
  "insertId": "...",
  "jsonPayload": {
    "log": "{\"key\": \"value\", \"key2\": \"value2\"}"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "...",
      "zone": "...",
      "instance_id": "..."
    }
  },
  "timestamp": "....",
  "labels": {
    "compute.googleapis.com/resource_name": "..."
  },
  "logName": "projects/.../logs/docker",
  "receiveTimestamp": "..."
}
```

How can I configure the Ops Agent to have the container logs structured in JSON in the `jsonPayload.log` field?

**Comment by alanhala** [comment] 2022-07-04 11:07
What's `field: message` for? You might need to have more than one processor in this case. The first one would parse the whole log and return the complete json log with the fields `log`, `stream` and `time`. From that json log you can extract the time. Lastly you need to parse again the json contained in the `log` key. Here's how it would look like:
```yaml
parse-json:
  type: parse_json
  time_key: time
  time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
parse-log:
  type: parse_json
  field: log
```

**Comment by PierreBart** [comment] 2022-07-05 17:50
I already tried your suggestion and unfortunately, it partially solves my issue.

When the second parser applies, the `time` and `stream` fields disappear.

I end up with the following structure in Cloud Logging:
```json
{
  "insertId": "...",
  "jsonPayload": {
    "key": "value",
    "key2": "value2"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "...",
      "zone": "...",
      "instance_id": "..."
    }
  },
  "timestamp": "....",
  "labels": {
    "compute.googleapis.com/resource_name": "..."
  },
  "logName": "projects/.../logs/docker",
  "receiveTimestamp": "..."
}
```

So the contents of the `log` field are correctly structured but all other fields are removed from the `jsonPayload`.

See this https://github.com/GoogleCloudPlatform/ops-agent/issues/209#issuecomment-924118412 for the logic behind the `field: message`.

**Comment by alanhala** [comment] 2022-07-05 18:23
Ah yeah, I don't know why it overrides instead of merging. There are some scenarios in which the override doesn't happen. But anyway... The time field I think by definition will be removed. Check the docs:
```
time_key: Optional. If the log entry provides a field with a timestamp, this option specifies the name of that field. The extracted value is used to set the timestamp field of the resulting [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) and is removed from the payload.
```

So if `stream` is not that important for you then you could skip it and it would kind of work.

**Comment by alanhala** [comment] 2022-07-05 18:30
> There are some scenarios in which the override doesn't happen. 

One scenario in which this doesn't happen is when you have this configuration:
```
logging:
  receivers:
    systemd-journald:
      type: systemd_journald
  processors:
    parse-json:
      type: parse_json
      field: MESSAGE
```

The logs coming from journald in that case have this similar structure:
```
{
  "_COMM" : "systemd",
  "_EXE" : "/usr/lib/systemd/systemd",
  "_CMDLINE" : "/usr/lib/systemd/systemd",
  "_SYSTEMD_CGROUP" : "/",
  "UNIT" : "nginx.service", 
  "MESSAGE" : "{ \"foo\": \"bar\" } ",
  "_SOURCE_REALTIME_TIMESTAMP" : "1422990364737973"
}
```
The result of this pipeline is this log:
```

{
  "_COMM" : "systemd",
  "_EXE" : "/usr/lib/systemd/systemd",
  "_CMDLINE" : "/usr/lib/systemd/systemd",
  "_SYSTEMD_CGROUP" : "/",
  "UNIT" : "nginx.service", 
  "foo": "bar",
  "_SOURCE_REALTIME_TIMESTAMP" : "1422990364737973"
}
```

I don't know why they behave differently though.

**Comment by ridwanmsharif** [comment] 2022-07-18 14:40
Can you share the Ops Agent version being used? As of [v2.17.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.17.0) we released #653 which makes it so that when you parse a specific field, the other fields that already exist don't get removed anymore. That change should make the steps here: https://github.com/GoogleCloudPlatform/ops-agent/issues/654#issuecomment-1175334587 work again. We can take a look at this further if the problem persists in any version > v2.17.0

**Comment by PierreBart** [comment] 2022-09-01 12:23
@ridwanmsharif Previously was used v2.16.0. I switched to v2.19.0 and tried the solution from https://github.com/GoogleCloudPlatform/ops-agent/issues/654#issuecomment-1173686022. Unfortunately, I end up with the same result as https://github.com/GoogleCloudPlatform/ops-agent/issues/654#issuecomment-1175334587.

**Comment by quentinmit** [comment] 2023-05-26 17:23
I'm closing this as a dupe of #650. Two stacked JSON parsers should be the way to solve this, but you need a way to not remove the fields from the first parser.

**Closed** 2023-05-26 17:23 UTC

**Comment by zhangbeibei** [comment] 2023-05-28 13:22
Hi, I met the same error in the latest new  version: 2.30.

**Comment by vinayattentive** [comment] 2025-01-24 09:33
Hi, just a quick question for the same scenario.

How are you managing different container logs in the GCP Logging dashboard? Like I want to view logs in the "All Log names" filed where I can select the container name and will able to view logs for that particular container.

Thanks in advance
